### ISSUE TITLE
手机上已绑定，但网页端扔提示需要激活，同时这个二维码手机扫描会提示无效

### ISSUE THREAD

**Issue by xiandan-erizo** [ao-space/ao.space#3]
<img width="975" alt="image" src="https://github.com/ao-space/ao.space/assets/23250774/1c60e9fe-d7a6-4fed-91c9-87d54e362ab2">
![image](https://github.com/ao-space/ao.space/assets/23250774/bd10a0b3-1867-4758-ab43-a18232c47979)

**Comment by xiandan-erizo** [comment]
docker部署，镜像tag是v1.0.0。 手机端是ios最新版
![image](https://github.com/ao-space/ao.space/assets/23250774/893b6e2a-dcbd-4c18-b5e5-4c203b52fc8b)

**Comment by jimmieme** [comment]
@xiandan-erizo  感谢反馈。绑定页面和 Web 访问页面是两个端口。绑定成功以后，就不用再访问绑定页面了，Web 可以通过 https://ao.space/login 来扫码登陆，如果局域网可链接，会自动提示切换到局域网访问（默认会是 *** .lan.ao.space 的网址）。登录页面也有提示通过局域网 IP 访问的地址。

**Comment by yuandaqing2009** [comment]
问题已解决，此issue关闭
