### ISSUE TITLE
通过https://testflight.apple.com/join/fsL70XY5连接无法下载开源版ios客户端

### ISSUE THREAD

**Issue by yymagicer** [ao-space/ao.space#7]
### What happened

通过https://testflight.apple.com/join/fsL70XY5连接无法下载开源版ios客户端

### What you expected to happen

通过https://testflight.apple.com/join/fsL70XY5可以下载开源版客户端

### How to reproduce it

直接点击https://testflight.apple.com/join/fsL70XY5
![91ed25ec81033c7392429507806586e](https://github.com/ao-space/ao.space/assets/11746302/6f842728-ba76-4ec7-8912-b344ebba6f08)

### Please tell us which version you are using （trial version or open-source version）

latest

**Comment by yuandaqing2009** [comment]
感谢您的反馈，已定位到问题 testFlight 版本过期，稍后将重新上传新的版本

**Comment by yuandaqing2009** [comment]
问题已解决，此issue关闭
